### ISSUE TITLE
Continue work on transition of `load_array` and `load_meta`

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/earthio#31]
How do `load_array` and `load_meta` from `earthio` relate to dataset loading capabilities in xarray?  

For examples:
 * Is there anything in the GeoTiff related logic for `earthio` that should be in `xarray`?  The `earthio` GeoTiff reader (with `rasterio`) was a Phase I thing before `xarray` added GeoTiff support.
 * Do `earthio`'s `load_array` and `load_meta` need to exist?  Can everything they do now be effectively pushed into `xarray`?  This may already be the case for the NetCDF reader.

**Comment by PeterDSteinberg** [comment]
#17 is the same issue but more specific to GeoTiff file support.

**Comment by PeterDSteinberg** [comment]
SHould it be called 'load_mldataset'?

**Comment by gbrener** [comment]
Hey @PeterDSteinberg, responding to your last comment - do you think it would make sense to call this `load_layers()`? Since we support passing _layer\_specs_ (via a kwarg) and we've already centralized around the "layer" as a central abstraction? Just an idea. It might help us keep _earthio_ decoupled conceptually from _elm_ and _xarray_filters_. Happy to keep `load_array()` for now though, if you're not in favor.

In terms of integrating with _xarray\_filters_ / _MLDataset_, I was thinking we could add a _MLDataset.load()_ method (or something similar), which could then call `earthio.load_array()` under the hood if necessary. That way we wouldn't have to return a data structure from `earthio.load_array()` that strictly depends on `xarray_filters`; perhaps it could be just a `xr.Dataset` or `xr.DataArray`? What do you think?

Regarding what we may be able to feed back to _xarray_ from the GeoTiff work in _earthio_ - if you recall the [table I created a few months ago](https://github.com/ContinuumIO/earthio/issues/17#issuecomment-308573406), I think we've closed the gap (to some extent) in xarray by preserving more of the GeoTiff metadata than was previously being collected. Also, the geotransform features -
 and I could be wrong here - were added to _MLDataset_ with the _Step_ work we did a few weeks ago.

**Comment by PeterDSteinberg** [comment]
* I like `load_layers` (plural form makes more sense + agreed that `layers` is more consistent with other work).  
* Let's go with your suggestion of having `load_layers` return `xr.Dataset` (they all return MLDataset now, I'm pretty sure, so it will be simple to change to the more general `xr.Dataset`
* `MLDataset.load` makes sense to me (importing `earthio` as an optional import wherever it is used in `xarray_filters`
* Thanks for reminder on the GeoTiff capabilities table - Let's make a notebook documenting that (I'll create a separate docs issue reminder - I think overall one of the potential confusions of new users is what returns/uses DataArray vs Dataset vs MLDataset)

**Comment by gbrener** [comment]
Cool, thanks for the feedback. I'll get started on the implementation shortly.

**Comment by gbrener** [comment]
Closing this issue now that #39 is merged. Opened https://github.com/ContinuumIO/xarray_filters/issues/43 to identify the remaining work left to be done, which is in the `xarray_filters` library.
